### ISSUE TITLE
Where could I read your paper?

### ISSUE THREAD

**Issue by thuyngch** [jshilong/SEPC#1]
Hi @jshilong ,

I am impressed by your comparison table. Thanks for publishing this repository.
I search your paper title but cannot find it.
How can I read your paper?

**Comment by jshilong** [comment]
The paper will appear in arXiv soon, we didn't expect somebody would find this repo first, you can refer this url first https://drive.google.com/open?id=1sXnji68qrpe51sJ837wJ56hr3dcbUHB9
