### ISSUE TITLE
How to set each epoch to be evaluated?

### ISSUE THREAD

**Issue by limengfei3675** [jshilong/SEPC#10]
evaluation = dict(interval=1, metric='mAP') 
Does interval = 1 mean that each epoch is evaluated? Why was it not evaluated during training.
thanks。

**Comment by jshilong** [comment]
https://github.com/jshilong/SEPC/blob/51e24ace1653cba6d3bc0ab536c6adb3b956c8dd/sepc/tools/train.py#L31
you need set --validate as true
