### ISSUE TITLE
why lconv and cconv in SPEC do not have padding value?

### ISSUE THREAD

**Issue by skidsaint** [jshilong/SEPC#13]
Thanks for the great work and code!
I want to understand the details of the SEPC so I check the code for the details of the new module. I found that in line37 of the spec.py the code is 
self.lconv = spec_conv(256, 256, kernel_size=3, dilation=1, part_deform=lcconv_deform)
The padding value is seem not specialized here. So my question is whether the padding is zero in lconv and cconv? If it is true, padding=0 in lconv and cconv is important for SEPC?

**Comment by jshilong** [comment]
I'm sorry for the confusion, It's just my fault. It's not important for the final results, But you may need to train It again for padding=1

**Comment by skidsaint** [comment]
Thanks for your reply !
