### ISSUE TITLE
Pyramid convolution

### ISSUE THREAD

**Issue by BlueCCircles** [jshilong/SEPC#14]
Hi, 
The open source code not contains the pyramid convolution? I only found the scale-equalizing pyramid convolution. 
When I read your paper, the SEPC only used to replace head, why not use it to restructure FPN (In the paper, pyramid convolution used to restructure FPN).

**Comment by jshilong** [comment]
We give all config about pconv, ibn_pvconv, sepc, sepc_lite 
about pconv
https://github.com/jshilong/SEPC/blob/51e24ace1653cba6d3bc0ab536c6adb3b956c8dd/sepc/exp/retina/pconv_retinanet.py#L24
In the code, Sepc  is added to pconv,
https://github.com/jshilong/SEPC/blob/51e24ace1653cba6d3bc0ab536c6adb3b956c8dd/sepc/self_mmdet/ops/dcn/sepc_dconv.py#L32
 I am sorry for  causing ambiguity,  you can combine the code and the paper to figure  it out

**Comment by BlueCCircles** [comment]
@jshilong Thanks for you reply. I found the configuration file for pyramid convolution. I will try it.
