### ISSUE TITLE
What is the RetinaNet baseline you use in your experiment?

### ISSUE THREAD

**Issue by Yuxin-CV** [jshilong/SEPC#15]
Hi~
Thanks for your great work!

I wonder what is the RetinaNet baseline you use in your experiment. In the Table 1 of the paper, for R-50-1x, the baseline of RetinaNet is AP = 35.7, similar to the "Focal Loss for Dense Object Detection". But in mmdet toolbox, the Box AP for RetinaNet is 36+ for a long time. 
So I want to make sure the RetinaNet baseline you use in your experiment.

Thanks!

**Comment by jshilong** [comment]
Hi , when prepare our paper last year, mmdet v2.0 not release yet, we use 1.0 as our baseline, you can find the baseline 
 https://github.com/open-mmlab/mmdetection/blob/v1.0.0/docs/MODEL_ZOO.md
I prepare the code base on v2.0 recently with higher baseline, thanks

**Comment by Yuxin-CV** [comment]
> Hi , when prepare our paper last year, mmdet v2.0 not release yet, we use 1.0 as our baseline, you can find the baseline
> https://github.com/open-mmlab/mmdetection/blob/v1.0.0/docs/MODEL_ZOO.md
> I prepare the code base on v2.0 recently with higher baseline, thanks

Thanks for your reply!
