### ISSUE TITLE
The question about PConv

### ISSUE THREAD

**Issue by wangjue-wzq** [jshilong/SEPC#16]
When I only use PConv to fuse three levels of features (top level and bottom level fuse two levels of features), the AP of small objects improves, but the AP of large objects decreases, do you have any suggestions? （only use PConv without iBN and deform convolution）

**Comment by jshilong** [comment]
COCO ？

**Comment by jshilong** [comment]
you may add more extra conv after pconv

**Comment by wangjue-wzq** [comment]
> COCO ？

Not a public data set. I applied PConv to Faster rcnn, I will try again, thanks for the reply.
