### ISSUE TITLE
Have you compared SEPC+FreeAnchor/SEPC+FSAF on X101?

### ISSUE THREAD

**Issue by tabsun** [jshilong/SEPC#2]
Great work!

**Comment by jshilong** [comment]
Thanks, You can get the results of SEPC+FreeAnchor(mAP 47.7 test) and the baseline(maP 44.9 test) from our paper, and about FSAF+SEPC ,we  get  46.5 mAP(44.1 baseline) on test, I may put the SOTA model to the google driver recently.
