### ISSUE TITLE
hello may i ask how you can calculate the correlation matrix of feature maps in fpn

### ISSUE THREAD

**Issue by GingerCohle** [jshilong/SEPC#20]
![image](https://user-images.githubusercontent.com/37873318/98912097-8bee4800-24bd-11eb-9456-cc377cc4fae1.png)
how to do that

**Comment by Birdylx** [comment]
Same question!  how to calculate the correlation between two different dimension feature maps?  for example, how do you calculate correlation between tensor A in shape of (HxWxC) and tensor B in shape of (H/2xW/2xC), I'm confused about it, do you scale them in the same dimension or stretch them to a vector and compute some distance of them?

**Comment by GingerCohle** [comment]
> Same question! how to calculate the correlation between two different dimension feature maps? for example, how do you calculate correlation between tensor A in shape of (HxWxC) and tensor B in shape of (H/2xW/2xC), I'm confused about it, do you scale them in the same dimension or stretch them to a vector and compute some distance of them?

![image](https://user-images.githubusercontent.com/37873318/99025229-46368b80-2560-11eb-8a10-a4c4205a1e2d.png)
see this

**Comment by jshilong** [comment]
@GingerCohle @Birdylx 
Sorry to reply so late, I had a ddl last month. 
We always resize the smaller feature map to the larger feature map，such as p4 to p3, p5 to p3，and for feature map correlation before the fpn，we  calculate the correlations of c2，c3，c4  that have just passed lateral convolution and p6 p7  from extra convs.
About the distance, we calculate the cosine distance of each point with 256 channels, then calculate the mean of these distances along spatial dimension(w,h).

**Comment by Birdylx** [comment]
@jshilong thanks a lot

**Comment by GingerCohle** [comment]
> @GingerCohle @Birdylx
> Sorry to reply so late, I had a ddl last month.
> We always resize the smaller feature map to the larger feature map，such as p4 to p3, p5 to p3，and for feature map correlation before the fpn，we calculate the correlations of c2，c3，c4 that have just passed lateral convolution and p6 p7 from extra convs.
> About the distance, we calculate the cosine distance of each point with 256 channels, then calculate the mean of these distances along spatial dimension(w,h).

ty so much
