### ISSUE TITLE
Is there a specific reason why we need to set img/gpu >=4 when ibn=True

### ISSUE THREAD

**Issue by Jossome** [jshilong/SEPC#21]
I saw this line in many config files: `iBN=True,  # when open, please set imgs/gpu >= 4`

Is this related to model performance? E.g., if I set imgs/gpu = 2, is there gonna be a noticeable drop in performance?

**Comment by jshilong** [comment]
Sure, if  set imgs/gpu = 2, there will be slight performance drop(~0.3mAP)
