### ISSUE TITLE
ATSS head 

### ISSUE THREAD

**Issue by dereyly** [jshilong/SEPC#4]
Thank you for great work!
Do you try add ATSS head to your experiments. How it compare with FreeAnchor+SEPC (SelfFreeAnchorRetinaHead)

**Comment by jshilong** [comment]
Sorry, ATSS didn't appear in arXiv when we submitted the paper, so we haven't got relevant experimental results.

**Comment by shinya7y** [comment]
Though I set iBN to False, the effectiveness of SEPC seems consistent.
Thank you for great work!

ATSS: 39.4 https://github.com/open-mmlab/mmdetection/tree/master/configs/atss
ATSS+SEPC (w/o iBN): 42.1 https://github.com/shinya7y/UniverseNet/tree/master/configs/universenet
`bbox_mAP_copypaste: 0.421 0.599 0.455 0.246 0.461 0.550`
