### ISSUE TITLE
Flops for deformable conv in PConv

### ISSUE THREAD

**Issue by tingtingliangvs** [jshilong/SEPC#5]
Hi there! I have a question about flops computation for deformable convolutions.
![image](https://user-images.githubusercontent.com/18143311/82443178-a24db500-9ad3-11ea-8646-2a447619bb1b.png)
In the paper, the PConv has the same Flops with that of FPN. Would you please share the flops computation method for deformable convolutions?  Thank you so much for your time!

**Comment by jshilong** [comment]
This part  is introduced in the appendix at the end of our paper，you can refer to https://arxiv.org/abs/2005.03101

**Comment by jshilong** [comment]
P.S:  Pconv does not include deformable convolution(sepc and sepc-lite do)
