### ISSUE TITLE
when I train my own model using your configure file and test, error happens.

### ISSUE THREAD

**Issue by LiangHann** [jshilong/SEPC#6]
when I train my own model using your configure file and test, error happens:
SEPC/mmdetection/mmdet/core/fp16/decorators.py", line 49, in new_func
    return old_func(*args, **kwargs)
TypeError: forward() missing 1 required positional argument: 'img_metas'

How to deal with this problem?
Many thanks.

**Comment by jshilong** [comment]
Can you describe more details for the error, especially how modify config， seems you didn't use standard data-pipeline , because 'img_metas' is a key in all mmdetection data-pipeline
