### ISSUE TITLE
How about using Pconv in FPN construction?

### ISSUE THREAD

**Issue by huangh12** [jshilong/SEPC#8]
Hi~
    Thanks for the inpsiring work.
    From the released code, the Pconv is employed after FPN is contructed, i.e., after p3~p3 are generated. So the Pconv is only used in the retinanet head. I'm curious that how about using pconv during the FPN construction.  Have you ever try that?

**Comment by jshilong** [comment]
Sure, you can try it , we used to remove FPN and only use 4 pconv, I remember just drop  <0.5 mAP

**Comment by huangh12** [comment]
Thanks for your reply.
